name: videoparse
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  collection: ^1.18.0
  webview_flutter: ^4.10.0
  webview_flutter_web: ^0.2.3+2
  gap: ^3.0.1
  logger: ^2.4.0
  http: ^1.2.2
  flutter_fullscreen: ^1.0.1
  protobuf: ^3.1.0
  protoc_plugin: ^21.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/json/
  fonts:
    - family: NotoSansSC
      fonts:
        - asset: assets/fonts/NotoSansSC.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto.ttf


